### ISSUE TITLE
MMU Support?

### ISSUE THREAD

**Issue by mateoconlechuga** [sergeykhbr/riscv_vhdl#13]
Hello, I was wondering if the River core (or perhaps integration of Rocket) supports any form of mmu? Thank you

**Comment by sergeykhbr** [comment]
Rocket chip has many configuration parameters including MMU. You can find examples with running Linux on it. 
I developed River CPU for usage in my embedded projects without intention to run Linux (not right now at least). So there's no ready-to-use MMU module.

**Comment by mateoconlechuga** [comment]
Great, thank you!
