### ISSUE TITLE
Problems with building (or rather starting) the debugger

### ISSUE THREAD

**Issue by nils1603** [sergeykhbr/riscv_vhdl#22]
Dear Sergey,

first of all thank you for creating this amazing project. I can't wait to put my hands on it and use it. Right now there seem to be some bugs when building (or rather starting) the debugger.

I installed qt5.7 and systemC from source as described in the README. I don't get any bugs during the building process of the debugger. But when I am trying to start it using some of the bash scripts I always get the same error:

```
eve@ubuntu: riscv_vhdl/debugger/linuxbuild/bin$ ./_run_functional_sim.sh 

Class GuiPluginClass not found

Error: can't instantiate configuration
```

Also there is a minor bug when creating the bash scripts. It seems that instead of adding the line break itself it just adds the '\n' to the script, which results in just one line, which cannot of course not be executed.

```
#!/bin/bash\nexport LD_LIBRARY_PATH=$(pwd):$(pwd)/qtlib\n./appdbg64g.exe -c ../../targets/functional_sim_gui.json "$@"
```

I am using Ubuntu 18.04

Thanks for any help :)

**Comment by sergeykhbr** [comment]
Hi,
It looks like the GUI plugin wasn't built successfully on your host. I've just cloned the clean repository and successfully built everything on Ubuntu:

    cd riscv_vhdl/debugger/makefiles/
    export QT_PATH=/opt/Qt5.11.1/5.11.1/gcc_64
    make

Probably you forget to export environment variable QT_PATH. Please check the file *makefiles/_gui_plugin-comp.err* for more details.
