### ISSUE TITLE
Zynq-7000

### ISSUE THREAD

**Issue by racarla** [sergeykhbr/riscv_vhdl#25]
Zynq-7000 implementation is ready to use?
And what it is the RISC-V specification version and extensions? 

Thank you!

**Comment by sergeykhbr** [comment]
It worked some time ago. Now I do not have such board and cannot check it. I can check only synthesis.

**Comment by sergeykhbr** [comment]
I use gcc 7.1 I suppose it supports the latest available user/privilege specifications.
