### ISSUE TITLE
Cannot find _run_functional_sim.sh

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [sergeykhbr/riscv_vhdl#27]
Cannot find **_run_functional_sim.sh** in debugger folder
 I Am following your readme and trying to do 
 "**Build and run custom FW like 'Hello World' example.**"
but am not able to find debugger/linuxbuild/bin/_run_functional_sim.sh

**Comment by sergeykhbr** [comment]
Could you please share your build-log files. They are in a folder **debugger/makefiles/*.err** with *.err extension. All warnings are treated as an errors in this project and probably newer version of gcc generates some warnings that do not occur on my host.

I've just tried clean build and it was successful.

      cd debugger/makefiles
      make clean
      make

**Comment by suhasskrishanmurthy** [comment]
i tried again it works
