### ISSUE TITLE
showing CPU is turned off

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [sergeykhbr/riscv_vhdl#28]
I followed the steps present in Readme for setting debugger 
and ran _run_functional_sim.sh 
after this a prompt cmd# came in that i tried loaded helloworld
cmd# loadelf /home/riscv/helloworld 
after this it showed reading some section 
after this i pressed F5 but its showing 
[25867098, "core0", "../src/common/generic/cpu_generic.cpp:428 CPU is turned-off"]

what am i doing wrong 
I reconfigured ip address to 192.168.0.53
using command 
sudo ifconfig eth0 192.168.0.53 netmask 255.255.255.0

**Comment by sergeykhbr** [comment]
This is definitely a bug. Thank you, I will fix it in a couple of days.

Some simulation platforms have a Power-on button to simulate Power Cycle. The demo Hello World system doesn't implement this functionality that's the root cause of the problem
