### ISSUE TITLE
Uart Conf

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [sergeykhbr/riscv_vhdl#31]
we want to use debugger for booting zephyr, In .ucf file you have connected uart1 to usb-uart convertor where as debug uart goes to LPC, So do we need to swap these as debugger is not able to connect uart in present situation.

**Comment by sergeykhbr** [comment]
Yes, you may swap these UARTS ports to be able debug via serial interface.
Take into notice that UART debug port is the master device and it automatically detects port baud rate on debugger connection (only first time after hard reset).
