### ISSUE TITLE
GNSS module

### ISSUE THREAD

**Issue by mfkiwl** [sergeykhbr/riscv_vhdl#38]
Hi there,

As you mentioned in the README and I found from the "gnsslib" folder, it seems there are RTL files and firmware for GNSS SDR receivers. I am quiet interested on it, as I am considering to build GNSS receivers with potential applications in small satellites. Are you convenient to share the RTL files and firmware? Thanks.

**Comment by sergeykhbr** [comment]
Hi,
I'm not going to publish source code of gnsslib in the nearest future. To work with this library out-of-the box you will need our customized mezzanine card or some RTL/FW tuning that I never tried to do.

In some special cases I can provide demonstration access but for the request it's better use request form on gnss-sensor.com site.
