### ISSUE TITLE
Build debugger with GUI failed: libdbg64g.so undefined reference

### ISSUE THREAD

**Issue by HollaHieu** [sergeykhbr/riscv_vhdl#40]
Hi Sergey! great project to learn from you!! I am running into a problem building and running Software models with GUI (Step 2 in your project). libdbg64g.so gives undefined reference and caused error when I run "make" in the "~/riscv_vhdl/debugger/makefiles" directory. Below is a screenshot of the problem. Can you give any hint on solving this? Thanks.

![Screenshot from 2021-07-05 17-10-13](https://user-images.githubusercontent.com/43841523/124455721-16204f00-ddb4-11eb-86f4-99f7ec7f937b.png)

**Comment by sergeykhbr** [comment]
Sorry friend for the delayed commit. Problem solved.
