### ISSUE TITLE
slurm dependency

### ISSUE THREAD

**Issue by ejessen** [sergeykhbr/riscv_vhdl#42]
I'm trying to get the design to compile & simulate - it looks very complete!  But... More advanced SW engineers use slurm, but a lot of people don't, especially HW engineers.  I've never used it.  Could you please add a RTL compile/simulate process that doesn't require slurm?

**Comment by sergeykhbr** [comment]
Additional target requires too much efforts to test and support. You can use Vivado toolchain or modify makefiles as you want.

**Comment by ejessen** [comment]
OK, it's not worth the effort to figure out what you did.
I'll go look elsewhere.

**Comment by ejessen** [comment]
Everyone else I know uses Makefile (shrug)
