### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by Pengnian** [sergeykhbr/riscv_vhdl#6]
Hi ,all

I want to compiling boot (riscv_vhdl\rocket_soc\fw\boot),but find some errors maybe causing  gun-toolchain version , please experts  explanation ! Thanks~

![compiling error](https://user-images.githubusercontent.com/26727603/29394524-60cf28c6-833d-11e7-8c0c-8b5a1856244d.png)

**Comment by sergeykhbr** [comment]
Hi,
You're building _bootimg_ with the flag **-march=rv64ima**, but gcc toolchain was built with the hardware FPU (default configuration).

I suggest to rebuild gcc with _**--disable-float**_ key or build _bootimg_ with the _-march=rv64imafd_.

**Comment by Pengnian** [comment]
Okay. Thanks very much，I will  try again！☺️ You explanation  very useful for  me！




Sent from Mail Master
On 08/17/2017 17:57, Sergey wrote:

Hi,
You're building bootimg with the flag -march=rv64ima, but gcc toolchain was built with the hardware FPU (default configuration).

I suggest to rebuild gcc with --disable-float key or build bootimg with the -march=rv64imafd.
