### ISSUE TITLE
Generate failed of helloworld  hex file

### ISSUE THREAD

**Issue by Pengnian** [sergeykhbr/riscv_vhdl#8]
Hi all,

I have used "make"  command in the directory of  "riscv_vhdl\rocket_soc\fw\helloworld\makefiles" want to generate helloworld hex file but the output is all zero.  Besides，the warning cannot solve it !  please tell me the reason. 

![111](https://user-images.githubusercontent.com/26727603/30674492-3b91d2d0-9ead-11e7-9c60-53e15004be9c.png)
![222](https://user-images.githubusercontent.com/26727603/30674643-337e246c-9eae-11e7-8da7-a3fe1daf51d6.png)

**Comment by sergeykhbr** [comment]
Hi,
you've specified start address (key -b) as 0, so it is possible that generated image at the beginning of file was nullified. Check the linker script *.ld or generated dump/list file to check where the 'code' section is started.

Default reset vector address is equal to 0x1000 and can be changed through the generic vhd-parameter.

**Comment by Pengnian** [comment]
@sergeykhbr

 Thank you very much~ 
 It's work~ Thanks your advice!
